name: Build and Publish NuGet Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore all projects
        run: dotnet restore

      - name: Build all projects
        run: dotnet build --configuration Release

      - name: Pack Logging library
        run: dotnet pack Logging/pawd.CoreLibrary.Logging.csproj --configuration Release --output ./artifacts

      - name: Pack HALForms library
        run: dotnet pack HALForms/pawd.CoreLibrary.HalForms.csproj --configuration Release --output ./artifacts

      - name: Publish packages to GitHub Packages
        run: |
          for file in ./artifacts/*.nupkg; do
            echo "Pushing $file..."
            dotnet nuget push "$file" \
              --source "https://nuget.pkg.github.com/pawd-app/index.json" \
              --api-key ${{ secrets.TOKEN }} \
              --skip-duplicate
          done
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.TOKEN }}
