name: Build and Publish NuGet Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore all projects
        run: dotnet restore

      - name: Build all projects
        run: dotnet build --configuration Release --no-restore

      - name: Pack projects with auto-incremented version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "Packaging with version $VERSION"

          for proj in $(find . -name '*.csproj'); do
            dotnet pack "$proj" \
              --configuration Release \
              --no-build \
              -p:PackageVersion=$VERSION \
              --output ./artifacts
          done

      - name: Publish to GitHub Packages
        run: |
          for nupkg in ./artifacts/*.nupkg; do
            echo "Publishing $nupkg"
            dotnet nuget push "$nupkg" \
              --source "https://nuget.pkg.github.com/pawd-app/index.json" \
              --api-key ${{ secrets.TOKEN }}
          done
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.TOKEN }}
